### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by HetviSoni** [HetviSoni/code-fraggers#1]
update the readme file properly and add the contribution steps. Also, add the Figma link in the readme file.
figma link : https://www.figma.com/file/jbHM5hTNpHikFhxmuFPZqM/CodeFraggersFinal?node-id=0%3A1

**Comment by ctnkaan** [comment]
Hey @HetviSoni, if this issue is still available I can do it today.

**Comment by HetviSoni** [comment]
yes sure

**Comment by HetviSoni** [comment]
Hey when will this be done?

**Comment by ctnkaan** [comment]
Hey sorry the work has been really heavy lately. I did a PR now.
