### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by parth-panchal** [HetviSoni/code-fraggers#12]
While I cannot contribute to any of the technical aspects for this project, I can draft a "code of conduct" to create a greater sense of inclusion and community for contributors. If you assign this issue to me I can get one ready for you in a couple of minutes.

**Comment by HetviSoni** [comment]
Yes Sure. Just one requirement :keep things short and sweet.

**Comment by parth-panchal** [comment]
Pull request #13 made. Please check
