### ISSUE TITLE
[Feature] Add a Contact Section and Contact Form

### ISSUE THREAD

**Issue by KIET7UKE** [HetviSoni/code-fraggers#15]
Hey @HetviSoni, I would also like to add a contact form also in your website so that visitors can easily get in touch with you. I would appreciate it if you would assign it to me.

**Comment by AbirSantra** [comment]
Can I work on this issue?

**Comment by HetviSoni** [comment]
> Hey @HetviSoni, I would also like to add a contact form also in your website so that visitors can easily get in touch with you. I would appreciate it if you would assign it to me.

Well thank you for your time and suggestions. But we need to make website according to design : https://www.figma.com/file/jbHM5hTNpHikFhxmuFPZqM/CodeFraggersFinal?node-id=0%3A1 .
So I would request you to take a look at this and pick up any issues from there. 
Thank you☺️

**Comment by KIET7UKE** [comment]
> > Hey @HetviSoni, I would also like to add a contact form also in your website so that visitors can easily get in touch with you. I would appreciate it if you would assign it to me.
> 
> Well thank you for your time and suggestions. But we need to make website according to design : https://www.figma.com/file/jbHM5hTNpHikFhxmuFPZqM/CodeFraggersFinal?node-id=0%3A1 .
> So I would request you to take a look at this and pick up any issues from there. 
> Thank you☺️

Okay so will raise a issue.
Also I have raised a issue on making the navbar of the website, kindly check and assign me in those.
Thanks
