### ISSUE TITLE
Sign-In

### ISSUE THREAD

**Issue by HetviSoni** [HetviSoni/code-fraggers#2]
The sign-in page is already half made. Complete it and link it to home page as in https://www.figma.com/file/jbHM5hTNpHikFhxmuFPZqM/CodeFraggersFinal?node-id=0%3A1

**Comment by Hariprasad19036** [comment]
I would like to work on this issue, kindly assign this to me under the hacktoberfest label!

**Comment by HetviSoni** [comment]
Yes sure

**Comment by manishgupta416** [comment]
Can you assign to me

**Comment by HetviSoni** [comment]
Hey @Hariprasad19036 when this will be done? Or should I assign this to next person?

**Comment by Hariprasad19036** [comment]
Hey @HetviSoni, Please assign it to the next person. I've been busy for the past week and wasn't able to focus on this. Apologies!
