### ISSUE TITLE
[Improvement] - Landing Page Design Improvement

### ISSUE THREAD

**Issue by AbirSantra** [HetviSoni/code-fraggers#20]
Hi, currently the landing page of the live website looks a bit different from the Figma design in terms of spacing and arrangement.

Live Website:
![image](https://user-images.githubusercontent.com/78201921/194739522-dbea4b0c-01f0-4cfb-bbe5-60052e48268b.png)

Figma Design:
![image](https://user-images.githubusercontent.com/78201921/194739538-09888018-9b0d-488d-95e9-e68a2c0dfd12.png)

I would like to work on this issue under Hacktoberfest 2022 to make it more like the Figma design.

Please let me know if the issue is approved and assign me to it.

Thank you

**Comment by HetviSoni** [comment]
Ig these differences are due to difference in screen ratio. 
Please elaborate on what changes you want to make.

**Comment by AbirSantra** [comment]
@HetviSoni 
Yes exactly. The Figma design was done at around 1440px width. However, as the screen size increases the elements are pulled away from each other, resulting in the design looking unnatural and not perfect. So I would like to add a max-width property and some flexboxes so that the elements don't get too separated and maintain a natural look when on ultrawide screens.

In the Figma design, the 'for fraggers' section stays in place with the 'for companies' section as well as the headline which looks perfect. However, on the live website, the 'for fraggers' section is going out of place and it is not looking good. 
Also, the distance between the hero image and hero content is too much on large screens which should not be the case.

I would like to improve the CSS so that the design stays consistent from medium to ultrawide screens.

**Comment by HetviSoni** [comment]
Yes nice observations. Assigning this to you👍
