### ISSUE TITLE
Responsive home page

### ISSUE THREAD

**Issue by HetviSoni** [HetviSoni/code-fraggers#36]
Make homepage responsive for mobile screen.

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue.

**Comment by OmkarDate29** [comment]
can you assign this to me

**Comment by HetviSoni** [comment]
Ok @Anish-Sarawgi assigning this to you as you were first.

**Comment by Anish-Sarawgi** [comment]
Hey @HetviSoni,
Please look into the changes.
