### ISSUE TITLE
Fixing Background on Sign up / Sign in Page 

### ISSUE THREAD

**Issue by horizenight** [HetviSoni/code-fraggers#41]
The current live design of Sign up and Sign in Page is 
![Screenshot 2022-10-15 154108](https://user-images.githubusercontent.com/76839614/195980876-505fa130-569c-447d-b511-b9f62015582c.png)
But this is the proposed design on the Figma files : 
![Screenshot 2022-10-15 154336](https://user-images.githubusercontent.com/76839614/195980961-bdac5b3b-1020-4d40-b008-bed9af4e1c6b.png)

This could be achieved in two ways: either making the modal section of the signup page or changing the background of the sign up route 

Kindly assign me this issue !

**Comment by HetviSoni** [comment]
You can do it by changing the background. Assigning it to you👍

**Comment by HetviSoni** [comment]
Hey when will this be done?
